### ISSUE TITLE
run in gpu error

### ISSUE THREAD

**Issue by zdx3578** [tambetm/gymexperiments#3]
Fitting imagination rollout model...
Done fitting, 200 timesteps covered.
Performing imagination rollout for 5 steps
Traceback (most recent call last):
  File "naf_ir.py", line 255, in <module>
    postobs, rewards, terminals = ir_model.predict(preobs, actions, timesteps + i)
  File "/home/ubuntu/gymexperiments/irmodel.py", line 107, in predict
    postob = np.random.multivariate_normal(obsmeans, obscov)
  File "mtrand.pyx", line 4689, in mtrand.RandomState.multivariate_normal (numpy/random/mtrand/mtrand.c:32216)
ValueError: mean must be 1 dimensional

do you run this code  in gpu?

before i am run it in cpu is ok! gpu server the theano is update to git latest version,maybe some lib conflict

**Comment by zdx3578** [comment]
pip sklearn is not update!

**Comment by tambetm** [comment]
I barely got the imagination rollout code working, but haven't had time to put it through tests. Let me know if it works for you!

**Comment by zdx3578** [comment]
when pip update sklearn； running ok！ thanks very much！
