### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by braham-snyder** [tambetm/gymexperiments#5]
Hi! Is there any chance you would be open to licensing this repo? I'd really like to tinker with your implementation of NAF.

**Comment by tambetm** [comment]
What do you mean by licensing? I could include LICENSE file in the repo, probably it would be something like [MIT license](https://opensource.org/licenses/MIT).

**Comment by braham-snyder** [comment]
The MIT license would be great!

**Comment by tambetm** [comment]
Done. But I never got NAF working with more than one actuator (i.e. MuJoco tasks), so be ready to experiment a lot. Also [Keras-RL](https://github.com/matthiasplappert/keras-rl) has DDPG and NAF implemented, maybe you can get some ideas from there.
